name: Update stats

on:
  schedule:
    - cron: "0 11 1 1,4,7,10 *" # 1st of Jan, Apr, Jul, Oct at 11 AM UTC
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.USER_TOKEN }}
      - name: Update README.md
        shell: bash
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'Daniel D.'
            git config user.email '73134670+DaniDoro@users.noreply.github.com'
            git add *.md
            git commit -m "Update README.md"
            git push
          fi
